### Create Student
POST localhost:8080/student
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "age": 19
}

### Get all student
GET localhost:8080/student


### Student filter
POST localhost:8080/student/filter?page=1&size=10
Content-Type: application/json

{
  "name": "Alish"
}

